#!/usr/bin/env python
# -*- coding: utf-8 -*-

# applet run-in-window
#	./wallpaperoptimizerApplet run-in-window

import sys
import os.path
import time
import logging

import pygtk
pygtk.require("2.0")
import gtk
import gnomeapplet

from WallpaperOptimizer.Applet import Applet

def factory(applet, iid):
	Applet(applet, iid)
	return gtk.TRUE

if len(sys.argv) == 2 and sys.argv[1] == "run-in-window":
	logging.debug('Running ... window mode.')
	main_window = gtk.Window(gtk.WINDOW_TOPLEVEL)
	main_window.set_title("Python Applet")
	main_window.connect("destroy", gtk.mainquit) 
	app = gnomeapplet.Applet()
	factory(app, None)
	app.reparent(main_window)
	main_window.show_all()
	gtk.main()

if __name__ == "__main__":
#	loglevel = logging.INFO
	loglevel = logging.DEBUG

	logging.basicConfig(level=loglevel
						, format='%(asctime)s %(levelname)5s %(message)s'
						, filename='/tmp/walloptApplet.log'
						, filemode='w')
	logging.info('Starting ... wallpaperoptimizer.')

	logging.debug('Running ... applet mode.')
	gnomeapplet.bonobo_factory("OAFIID:wallpaperoptimizerApplet_Factory"
							, gnomeapplet.Applet.__gtype__
							, "wallpaper changer"
							, "1.0"
							, factory)
