#!/usr/bin/env python
# -*- coding: utf-8 -*-

# singlerun
#	./wallpaperoptimizer  ../2560x1920.jpg ../1500x844.jpg -C -W
# background
#	./wallpaperoptimizer -D -i 5 -W
# applet run-in-window
#	./wallpaperoptimizer -W

import sys
import os.path
import time
import logging

import pygtk
pygtk.require("2.0")
import gtk
import gnomeapplet
import gnome.ui
try:
	import glib as glibobj
except:
	try:
		import gobject as glibobj
	except:
		sys.exit(2)

from WallpaperOptimizer.Options import Options
from WallpaperOptimizer.Core import Core
from WallpaperOptimizer.Applet import Applet
from optparse import OptionValueError

def factory(applet, iid):
	Applet(applet, iid)
	return gtk.TRUE

#if len(sys.argv) == 2 and sys.argv[1] == "run-in-window":
#	analize commandline option
#try:
#	option = Options()
#except OptionValueError, msg:
#	logging.error('** OptionValueError: %s. ' % msg)
#	sys.exit(2)
#Verbose = option.getVerbose()

if __name__ == "__main__":
#	loglevel = logging.INFO
	loglevel = logging.DEBUG

	logging.basicConfig(level=loglevel
						, format='%(asctime)s %(levelname)5s %(message)s'
						, filename='/tmp/wallposit.log'
						, filemode='w')
	logging.info('Starting ... wallpaperoptimizer.')

	logging.debug('Running ... applet mode.')
	gnomeapplet.bonobo_factory("OAFIID:wallpaperoptimizer_Factory"
							, gnomeapplet.Applet.__gtype__
							, "wallpaper changer"
							, "1.0"
							, factory)
