#!/usr/bin/env python
# -*- coding: utf-8 -*-

""" wallpaperoptimizer start program

wallpaperoptimizer is multi wallpaper changer.
"""

# <singlerun>
#	wallpaperoptimiz  ../2560x1920.jpg ../1500x844.jpg -C
# <background>
#	wallpaperoptimiz -D -i 5
# <applet window mode>
#	wallpaperoptimiz -W
# <applet>
#	in GNOME panel

import sys
import logging

import os
import os.path
from optparse import OptionValueError

import harite.WallpaperOptimizer as WallpaperOptimizer
from harite.WallpaperOptimizer.Options import Options
from harite.WallpaperOptimizer.Core import Core


def do_main():
    try:
        option = Options()
    except OptionValueError as msg:
        logging.error('** OptionValueError: %s. ' % msg)
        sys.exit(2)

    Verbose = option.getVerbose()
    if Verbose:
        loglevel = logging.DEBUG
    else:
        loglevel = logging.INFO

    logfile = os.path.join(WallpaperOptimizer.USERENVDIR, 'wallopt.log')
    logging.basicConfig(
        level=loglevel,
        format='%(asctime)s %(levelname)5s %(message)s',
        filename=logfile,
        filemode='a')
    logging.info('Starting ... wallpaperoptimizer.')

    # CLI-first execution: avoid importing GUI/Starter unless window mode requested
    if option.getWindow():
        # window mode requires GUI support; delay importing StarterFactory
        try:
            from harite.WallpaperOptimizer.StarterFactory import StarterFactory
        except Exception as e:
            logging.error('GUI not available: %s' % e)
            sys.exit(2)
        starterfactory = StarterFactory()
        starter = starterfactory.create(WallpaperOptimizer.WINDOWMANAGER)
        # ensure DISPLAY is set for GUI
        if os.getenv('DISPLAY', None) is None:
            print("Please set DISPLAY environment for window mode.")
            sys.exit(2)
        starter.start(option, logging)
    else:
        # non-window CLI flow: call Core directly
        # If display size not provided, infer from input images so Core can run in CLI-only mode
        if not option.getWindow():
            try:
                from harite.WallpaperOptimizer.Imaging.ImgFile import ImgFile
                # infer sizes from args if not provided
                try:
                    larg = option.getLArg()
                except Exception:
                    larg = None
                try:
                    rarg = option.getRArg()
                except Exception:
                    rarg = None

                if option.getLSize() is None and larg:
                    try:
                        li = ImgFile(larg)
                        option.opts.size[0] = f"{li.Size.w}x{li.Size.h}"
                    except Exception:
                        option.opts.size[0] = '1x1'
                if option.getRSize() is None:
                    if rarg:
                        try:
                            ri = ImgFile(rarg)
                            option.opts.size[1] = f"{ri.Size.w}x{ri.Size.h}"
                        except Exception:
                            option.opts.size[1] = option.opts.size[0]
                    else:
                        option.opts.size[1] = option.opts.size[0] or '1x1'
            except Exception:
                # best-effort: fall back to minimal 1x1 sizes
                if option.getLSize() is None:
                    option.opts.size[0] = '1x1'
                if option.getRSize() is None:
                    option.opts.size[1] = '1x1'

        core = Core(option)
        try:
            if option.getDaemonize():
                core.background()
            else:
                core.singlerun()
        except Core.CoreRuntimeError as msg:
            logging.error('** CoreRuntimeError: %s. ' % msg.value)
            sys.exit(2)

    logging.info('Quit ... wallpaperoptimizer.')


if __name__ == "__main__":
    do_main()
    sys.exit(0)
